export type Project = {
  slug: string;
  title: string;
  category: string;
  tagline: string;
  description: string;
  tech: string[];
  outcome: string;
  gradient: string;
<<<<<<< HEAD
  coverImage: string;
};

function coverFor(slug: string) {
  return new URL(`../assets/portfolio/${slug}.webp`, import.meta.url).href;
}

export const projects: Project[] = [
  { slug: "nova-ai-analytics", title: "Nova AI Analytics", category: "AI / ML", tagline: "Real-time predictive analytics for fintech.", description: "Custom LLM-powered analytics platform ingesting 40M+ events/day, delivering trade signals with sub-second latency.", tech: ["Python", "TensorFlow", "PostgreSQL", "AWS", "React"], outcome: "+38% forecast accuracy · 60% faster insights", gradient: "from-[#3B82F6] to-[#8B5CF6]", coverImage: coverFor("nova-ai-analytics") },
  { slug: "helix-saas", title: "Helix SaaS Platform", category: "SaaS", tagline: "Enterprise-grade workflow automation.", description: "Multi-tenant SaaS handling automation for 200+ mid-market companies. Built end-to-end from schema to onboarding.", tech: ["Node.js", "React", "PostgreSQL", "Docker", "Stripe"], outcome: "$3M ARR in 14 months", gradient: "from-[#22D3EE] to-[#3B82F6]", coverImage: coverFor("helix-saas") },
  { slug: "orbit-mobile", title: "Orbit Mobile", category: "Mobile", tagline: "Cross-platform social fitness app.", description: "React Native app with real-time coaching, wearable sync, and live group workouts.", tech: ["React Native", "Node.js", "Firebase", "HealthKit"], outcome: "500k+ installs · 4.9★ average rating", gradient: "from-[#8B5CF6] to-[#22D3EE]", coverImage: coverFor("orbit-mobile") },
  { slug: "atlas-cloud", title: "Atlas Cloud", category: "Cloud", tagline: "Multi-region Kubernetes migration.", description: "Migrated a global logistics operator from monolith to Kubernetes across AWS, Azure, and GCP.", tech: ["Kubernetes", "Terraform", "AWS", "GCP", "Azure"], outcome: "70% infra cost reduction", gradient: "from-[#3B82F6] to-[#22D3EE]", coverImage: coverFor("atlas-cloud") },
  { slug: "prism-design", title: "Prism Design System", category: "UI/UX", tagline: "Design language for a healthtech scale-up.", description: "Full design language including tokens, 240+ components, and a Storybook doc site.", tech: ["Figma", "React", "TypeScript", "Storybook"], outcome: "3× faster feature delivery", gradient: "from-[#8B5CF6] to-[#3B82F6]", coverImage: coverFor("prism-design") },
  { slug: "vertex-erp", title: "Vertex ERP", category: "Software", tagline: "Custom ERP for a manufacturing group.", description: "Bespoke ERP replacing 6 legacy tools; inventory, HR, finance, and production planning in one workspace.", tech: ["Node.js", "React", "PostgreSQL", "Kafka"], outcome: "$1.2M/yr operational savings", gradient: "from-[#22D3EE] to-[#8B5CF6]", coverImage: coverFor("vertex-erp") },
  { slug: "lumen-vision", title: "Lumen Vision", category: "AI / ML", tagline: "Computer vision for retail loss prevention.", description: "On-prem vision model deployed across 400 store cameras, detecting theft patterns with 96% precision.", tech: ["PyTorch", "OpenCV", "Docker", "NVIDIA Triton"], outcome: "-42% shrinkage in pilot chain", gradient: "from-[#3B82F6] to-[#8B5CF6]", coverImage: coverFor("lumen-vision") },
  { slug: "cascade-web", title: "Cascade Web", category: "Web Dev", tagline: "Editorial platform for a Middle-East publisher.", description: "Headless CMS + Next.js frontend serving 12M monthly readers with sub-second TTFB.", tech: ["Next.js", "Sanity", "Vercel", "Redis"], outcome: "LCP 0.9s · +55% pageviews", gradient: "from-[#22D3EE] to-[#3B82F6]", coverImage: coverFor("cascade-web") },
  { slug: "signal-automation", title: "Signal Automation", category: "Automation", tagline: "AI-driven back-office automation.", description: "RPA + LLM hybrid automating invoicing, KYC review, and support ticket triage for a European bank.", tech: ["Python", "LangChain", "n8n", "Azure"], outcome: "12,000 hours saved / quarter", gradient: "from-[#8B5CF6] to-[#22D3EE]", coverImage: coverFor("signal-automation") },
  { slug: "mirage-brand", title: "Mirage Brand Studio", category: "Digital", tagline: "Full brand + digital campaign relaunch.", description: "Brand identity, product photography, digital campaign, and a Framer marketing site for a UK DTC brand.", tech: ["Figma", "Framer", "Meta Ads", "GA4"], outcome: "+180% qualified traffic", gradient: "from-[#3B82F6] to-[#22D3EE]", coverImage: coverFor("mirage-brand") },
  { slug: "quasar-chat", title: "Quasar Chat", category: "AI / ML", tagline: "Enterprise assistant grounded in company data.", description: "RAG-based assistant across 6TB internal docs with per-team retrieval and audit trails.", tech: ["OpenAI", "Pinecone", "Node.js", "React"], outcome: "94% question resolution rate", gradient: "from-[#8B5CF6] to-[#3B82F6]", coverImage: coverFor("quasar-chat") },
  { slug: "meridian-fintech", title: "Meridian Fintech", category: "SaaS", tagline: "Cross-border payments platform.", description: "Full-stack platform enabling B2B FX and payouts across 40+ corridors with regulatory compliance.", tech: ["Go", "React", "PostgreSQL", "Kafka"], outcome: "$120M processed in year one", gradient: "from-[#22D3EE] to-[#8B5CF6]", coverImage: coverFor("meridian-fintech") },
  { slug: "nebula-education", title: "Nebula Education", category: "Web Dev", tagline: "Adaptive learning for K-12 in the UAE.", description: "Personalized curriculum platform with AI tutoring, gamified progress, and parent dashboards.", tech: ["React", "Django", "PostgreSQL", "GPT-4"], outcome: "Adopted by 60+ schools", gradient: "from-[#3B82F6] to-[#8B5CF6]", coverImage: coverFor("nebula-education") },
  { slug: "forge-devops", title: "Forge DevOps", category: "Cloud", tagline: "CI/CD platform for a scale-up.", description: "Custom internal developer platform on Kubernetes with self-service environments.", tech: ["Kubernetes", "ArgoCD", "GitHub Actions", "Terraform"], outcome: "Deploys reduced 45min → 4min", gradient: "from-[#22D3EE] to-[#3B82F6]", coverImage: coverFor("forge-devops") },
  { slug: "aria-voice", title: "Aria Voice", category: "AI / ML", tagline: "Multilingual voice assistant for hospitality.", description: "Voice-first concierge for luxury hotels supporting 12 languages with contextual memory.", tech: ["Whisper", "GPT-4o", "Twilio", "Node.js"], outcome: "Deployed in 20 hotels globally", gradient: "from-[#8B5CF6] to-[#22D3EE]", coverImage: coverFor("aria-voice") },
  { slug: "kite-mobile", title: "Kite Mobile", category: "Mobile", tagline: "iOS + Android for a logistics startup.", description: "Driver-facing app with route optimization and offline-first sync.", tech: ["Flutter", "Firebase", "Mapbox", "Node.js"], outcome: "35% faster last-mile delivery", gradient: "from-[#3B82F6] to-[#22D3EE]", coverImage: coverFor("kite-mobile") },
  { slug: "lattice-ux", title: "Lattice UX Overhaul", category: "UI/UX", tagline: "Repositioning a legacy SaaS for scale.", description: "Full UX audit, IA rework, and design system for a 15-year-old enterprise tool.", tech: ["Figma", "Maze", "React", "TypeScript"], outcome: "+72% activation rate", gradient: "from-[#8B5CF6] to-[#3B82F6]", coverImage: coverFor("lattice-ux") },
  { slug: "pulse-marketplace", title: "Pulse Marketplace", category: "SaaS", tagline: "Two-sided creator marketplace.", description: "End-to-end marketplace with escrow, disputes, and creator analytics for the MENA region.", tech: ["Next.js", "Stripe Connect", "PostgreSQL", "Redis"], outcome: "15k active creators in year one", gradient: "from-[#22D3EE] to-[#8B5CF6]", coverImage: coverFor("pulse-marketplace") },
  { slug: "beacon-iot", title: "Beacon IoT", category: "Software", tagline: "Industrial IoT monitoring platform.", description: "Real-time sensor telemetry ingestion, ML anomaly detection, and Grafana-based dashboards.", tech: ["Rust", "InfluxDB", "MQTT", "Grafana"], outcome: "Predicted 3 major outages", gradient: "from-[#3B82F6] to-[#8B5CF6]", coverImage: coverFor("beacon-iot") },
  { slug: "halo-brand-web", title: "Halo Brand Web", category: "Web Dev", tagline: "Interactive marketing site with WebGL.", description: "Award-worthy marketing site with WebGL storytelling and interactive product configurator.", tech: ["Three.js", "GSAP", "Next.js", "Sanity"], outcome: "Awwwards Site of the Day", gradient: "from-[#22D3EE] to-[#3B82F6]", coverImage: coverFor("halo-brand-web") },
];

export const getProject = (slug: string) => projects.find((p) => p.slug === slug);
=======
};

export const projects: Project[] = [
  { slug: "nova-ai-analytics", title: "Nova AI Analytics", category: "AI / ML", tagline: "Real-time predictive analytics for fintech.", description: "Custom LLM-powered analytics platform ingesting 40M+ events/day, delivering trade signals with sub-second latency.", tech: ["Python", "TensorFlow", "PostgreSQL", "AWS", "React"], outcome: "+38% forecast accuracy · 60% faster insights", gradient: "from-[#3B82F6] to-[#8B5CF6]" },
  { slug: "helix-saas", title: "Helix SaaS Platform", category: "SaaS", tagline: "Enterprise-grade workflow automation.", description: "Multi-tenant SaaS handling automation for 200+ mid-market companies. Built end-to-end from schema to onboarding.", tech: ["Node.js", "React", "PostgreSQL", "Docker", "Stripe"], outcome: "$3M ARR in 14 months", gradient: "from-[#22D3EE] to-[#3B82F6]" },
  { slug: "orbit-mobile", title: "Orbit Mobile", category: "Mobile", tagline: "Cross-platform social fitness app.", description: "React Native app with real-time coaching, wearable sync, and live group workouts.", tech: ["React Native", "Node.js", "Firebase", "HealthKit"], outcome: "500k+ installs · 4.9★ average rating", gradient: "from-[#8B5CF6] to-[#22D3EE]" },
  { slug: "atlas-cloud", title: "Atlas Cloud", category: "Cloud", tagline: "Multi-region Kubernetes migration.", description: "Migrated a global logistics operator from monolith to Kubernetes across AWS, Azure, and GCP.", tech: ["Kubernetes", "Terraform", "AWS", "GCP", "Azure"], outcome: "70% infra cost reduction", gradient: "from-[#3B82F6] to-[#22D3EE]" },
  { slug: "prism-design", title: "Prism Design System", category: "UI/UX", tagline: "Design language for a healthtech scale-up.", description: "Full design language including tokens, 240+ components, and a Storybook doc site.", tech: ["Figma", "React", "TypeScript", "Storybook"], outcome: "3× faster feature delivery", gradient: "from-[#8B5CF6] to-[#3B82F6]" },
  { slug: "vertex-erp", title: "Vertex ERP", category: "Software", tagline: "Custom ERP for a manufacturing group.", description: "Bespoke ERP replacing 6 legacy tools; inventory, HR, finance, and production planning in one workspace.", tech: ["Node.js", "React", "PostgreSQL", "Kafka"], outcome: "$1.2M/yr operational savings", gradient: "from-[#22D3EE] to-[#8B5CF6]" },
  { slug: "lumen-vision", title: "Lumen Vision", category: "AI / ML", tagline: "Computer vision for retail loss prevention.", description: "On-prem vision model deployed across 400 store cameras, detecting theft patterns with 96% precision.", tech: ["PyTorch", "OpenCV", "Docker", "NVIDIA Triton"], outcome: "-42% shrinkage in pilot chain", gradient: "from-[#3B82F6] to-[#8B5CF6]" },
  { slug: "cascade-web", title: "Cascade Web", category: "Web Dev", tagline: "Editorial platform for a Middle-East publisher.", description: "Headless CMS + Next.js frontend serving 12M monthly readers with sub-second TTFB.", tech: ["Next.js", "Sanity", "Vercel", "Redis"], outcome: "LCP 0.9s · +55% pageviews", gradient: "from-[#22D3EE] to-[#3B82F6]" },
  { slug: "signal-automation", title: "Signal Automation", category: "Automation", tagline: "AI-driven back-office automation.", description: "RPA + LLM hybrid automating invoicing, KYC review, and support ticket triage for a European bank.", tech: ["Python", "LangChain", "n8n", "Azure"], outcome: "12,000 hours saved / quarter", gradient: "from-[#8B5CF6] to-[#22D3EE]" },
  { slug: "mirage-brand", title: "Mirage Brand Studio", category: "Digital", tagline: "Full brand + digital campaign relaunch.", description: "Brand identity, product photography, digital campaign, and a Framer marketing site for a UK DTC brand.", tech: ["Figma", "Framer", "Meta Ads", "GA4"], outcome: "+180% qualified traffic", gradient: "from-[#3B82F6] to-[#22D3EE]" },
  { slug: "quasar-chat", title: "Quasar Chat", category: "AI / ML", tagline: "Enterprise assistant grounded in company data.", description: "RAG-based assistant across 6TB internal docs with per-team retrieval and audit trails.", tech: ["OpenAI", "Pinecone", "Node.js", "React"], outcome: "94% question resolution rate", gradient: "from-[#8B5CF6] to-[#3B82F6]" },
  { slug: "meridian-fintech", title: "Meridian Fintech", category: "SaaS", tagline: "Cross-border payments platform.", description: "Full-stack platform enabling B2B FX and payouts across 40+ corridors with regulatory compliance.", tech: ["Go", "React", "PostgreSQL", "Kafka"], outcome: "$120M processed in year one", gradient: "from-[#22D3EE] to-[#8B5CF6]" },
  { slug: "nebula-education", title: "Nebula Education", category: "Web Dev", tagline: "Adaptive learning for K-12 in the UAE.", description: "Personalized curriculum platform with AI tutoring, gamified progress, and parent dashboards.", tech: ["React", "Django", "PostgreSQL", "GPT-4"], outcome: "Adopted by 60+ schools", gradient: "from-[#3B82F6] to-[#8B5CF6]" },
  { slug: "forge-devops", title: "Forge DevOps", category: "Cloud", tagline: "CI/CD platform for a scale-up.", description: "Custom internal developer platform on Kubernetes with self-service environments.", tech: ["Kubernetes", "ArgoCD", "GitHub Actions", "Terraform"], outcome: "Deploys reduced 45min → 4min", gradient: "from-[#22D3EE] to-[#3B82F6]" },
  { slug: "aria-voice", title: "Aria Voice", category: "AI / ML", tagline: "Multilingual voice assistant for hospitality.", description: "Voice-first concierge for luxury hotels supporting 12 languages with contextual memory.", tech: ["Whisper", "GPT-4o", "Twilio", "Node.js"], outcome: "Deployed in 20 hotels globally", gradient: "from-[#8B5CF6] to-[#22D3EE]" },
  { slug: "kite-mobile", title: "Kite Mobile", category: "Mobile", tagline: "iOS + Android for a logistics startup.", description: "Driver-facing app with route optimization and offline-first sync.", tech: ["Flutter", "Firebase", "Mapbox", "Node.js"], outcome: "35% faster last-mile delivery", gradient: "from-[#3B82F6] to-[#22D3EE]" },
  { slug: "lattice-ux", title: "Lattice UX Overhaul", category: "UI/UX", tagline: "Repositioning a legacy SaaS for scale.", description: "Full UX audit, IA rework, and design system for a 15-year-old enterprise tool.", tech: ["Figma", "Maze", "React", "TypeScript"], outcome: "+72% activation rate", gradient: "from-[#8B5CF6] to-[#3B82F6]" },
  { slug: "pulse-marketplace", title: "Pulse Marketplace", category: "SaaS", tagline: "Two-sided creator marketplace.", description: "End-to-end marketplace with escrow, disputes, and creator analytics for the MENA region.", tech: ["Next.js", "Stripe Connect", "PostgreSQL", "Redis"], outcome: "15k active creators in year one", gradient: "from-[#22D3EE] to-[#8B5CF6]" },
  { slug: "beacon-iot", title: "Beacon IoT", category: "Software", tagline: "Industrial IoT monitoring platform.", description: "Real-time sensor telemetry ingestion, ML anomaly detection, and Grafana-based dashboards.", tech: ["Rust", "InfluxDB", "MQTT", "Grafana"], outcome: "Predicted 3 major outages", gradient: "from-[#3B82F6] to-[#8B5CF6]" },
  { slug: "halo-brand-web", title: "Halo Brand Web", category: "Web Dev", tagline: "Interactive marketing site with WebGL.", description: "Award-worthy marketing site with WebGL storytelling and interactive product configurator.", tech: ["Three.js", "GSAP", "Next.js", "Sanity"], outcome: "Awwwards Site of the Day", gradient: "from-[#22D3EE] to-[#3B82F6]" },
];

export const getProject = (slug: string) => projects.find((p) => p.slug === slug);
>>>>>>> a25318459c6d5f0d463fa1ed2c0fa7553a6d1ef2
